### ISSUE TITLE
looks pasted ngl

### ISSUE THREAD

**Issue by xxmyn** [zphrus/ChadAlphaMales#27]

**Comment by zphrus** [comment]
Don't know what you're talking about, we definitely didn't paste wdym bro nah nahhhh
(Fware also was pasted from CAM 😢)

**Comment by xxmyn** [comment]
> Don't know what you're talking about, we definitely didn't paste wdym bro nah nahhhh (Fware also was pasted from CAM 😢)

not true not true not true fware is fully self coded not true not pasted only cam is pasted not true this is slander this is a satirical comment this is fake news not true deboonked multiple times snopes said fware was self coded show your sources this is an untrue statement

**Comment by zphrus** [comment]
> > Don't know what you're talking about, we definitely didn't paste wdym bro nah nahhhh (Fware also was pasted from CAM 😢)
> 
> not true not true not true fware is fully self coded not true not pasted only cam is pasted not true this is slander this is a satirical comment this is fake news not true deboonked multiple times snopes said fware was self coded show your sources this is an untrue statement

Nahhhhh it ain't nahh like lmao 🤣🤣🤣😂😂 I'm dead lmaooo 💀💀💀 Like lollllll cam is pasted? that's the joke of all time xDDDD
